Feat/joey/account
joeywang321/forum pull request #1
Opened 2023-04-04 02:17 UTC by joeywang321

Add account context and registration features

2023-04-11 07:56 UTC, fahchen requested changes

2023-04-11 10:00 UTC, fahchen submitted a review, later dismissed

2023-04-11 10:01 UTC, fahchen requested changes
对 `.github/workflows/elixir.yml` 的修改不应该存在任何一个 commit 里面

2023-04-12 03:53 UTC, fahchen commented
message 的 scope 后面要有冒号

2023-04-17 01:56 UTC, joeywang321 commented
@fahchen sf,有时间看看这个pr还有没有问题，没有问题我就提下一个了

2023-04-17 03:58 UTC, fahchen approved these changes

2023-04-17 03:58 UTC, fahchen commented on lib/forum/accounts.ex
> +  @spec create(map) :: any()
返回值不能写 any

2023-04-17 06:15 UTC, merged