Feat/joey/account
joeywang321/forum pull request #5
Opened 2023-04-19 03:28 UTC by joeywang321

2023-04-19 06:31 UTC, joeywang321 commented
sf，没找到这个 dialyzer 报错的原因。

2023-04-19 07:43 UTC, fahchen requested changes

2023-04-19 07:43 UTC, fahchen commented on lib/forum_web/auth/set_account.ex
这个应该是一个 plug 吧，使用 `@behaviour Plug` 声明一下

2023-04-19 07:43 UTC, fahchen commented on lib/forum_web/auth/set_account.ex
> +          user = Forum.Repo.preload(Accounts.get_user!(user_id), [:profile])
这里一定能找到 user 吗？

2023-04-19 07:43 UTC, fahchen commented on lib/forum_web/auth/set_account.ex
> +    end
我咋感觉你这部分做得有问题呢
这个文件 `lib/forum_web/auth/pipeline.ex` 有一些 plugs，最后一个 `Guardian.Plug.LoadResource` 会把 source load 出来，但这里又没用这个 source，又回到 assigns 和 session 里面去取了

2023-04-19 07:43 UTC, fahchen commented on lib/forum_web/controllers/account_controller.ex
> +        |> Plug.Conn.put_session(:user_id, user.id)
前后端分离后，不存在 session 了哦

2023-04-19 07:43 UTC, fahchen commented on lib/forum_web/router.ex
> +    plug :fetch_session
对于 api 不存在 session 的，authentication 是通过 token 去做的

2023-04-20 07:20 UTC, fahchen requested changes
还有个问题没改到

2023-04-20 07:47 UTC, fahchen requested changes

2023-04-20 07:47 UTC, fahchen commented on lib/forum_web/auth/set_account.ex
> +  @spec init(Keyword.t()) :: :ok
```suggestion
  @impl Plug
```

2023-04-20 09:04 UTC, fahchen requested changes
看下 behaviour 的文档，补一下这部分的知识

2023-04-20 09:04 UTC, fahchen commented on lib/forum_web/auth/set_account.ex
> +  @spec call(Plug.Conn.t(), Keyword.t()) :: Plug.Conn.t()
```suggestion
```

2023-04-21 06:49 UTC, joeywang321 commented on lib/forum_web/auth/set_account.ex
> +  @spec call(Plug.Conn.t(), Keyword.t()) :: Plug.Conn.t()
基本看完了关于定义和声明一些特殊的语法和元数据。和rust的traits的设计非常相似（也可能是我没有理解到）感觉是一个非常强大的功能

2023-04-21 06:54 UTC, joeywang321 commented on lib/forum_web/auth/set_account.ex
> +  @spec call(Plug.Conn.t(), Keyword.t()) :: Plug.Conn.t()
其他的包括@module_attribute，还有其他的都看过了

2023-04-21 07:09 UTC, fahchen approved these changes

2023-04-21 07:17 UTC, merged